version: "3.9"
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_DEBUG=1
    volumes:
      - .:/app
  db:
    image: "postgres"
    ports:
      - "50431:5432"
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=admin1
      - POSTGRES_PASSWORD=admin123
    volumes:
      - ./data/db:/var/lib/postgresql/data
